name: conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - flask=3.1.0
  - flask-login=0.6.3
  - flask-sqlalchemy=3.1.1
  - flask-wtf=1.2.2
  - flask-migrate=4.*
  - click=8.1.8
  - jinja2=3.1.6
  - itsdangerous=2.2.0
  - email-validator=2.2.0
  - python-dotenv=1.0.1
  - sqlalchemy=2.0.37
  - greenlet=3.1.1
  - cryptography=43.0.3
  - dnspython=2.4.2
  - wtforms=3.2.1
  - pytest=7.*
  - faker=19.*
  - ca-certificates=2025.2.25
  - openssl=3.5.0
  - zlib=1.2.13
  - libffi=3.4.4
  - ncurses=6.4
  - tk=8.6.14
  - xz=5.4.6
  - tzdata=2024b